package vistas;

import javax.swing.JOptionPane;



public class Vprincipal extends javax.swing.JFrame {
    
    private Vprod vprd;
    
    /**
     * Creates new form Vprincipal
     */
    public Vprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_sistema = new javax.swing.JMenu();
        Item_salir = new javax.swing.JMenuItem();
        Item_sesion_close = new javax.swing.JMenuItem();
        Menu_producto = new javax.swing.JMenu();
        Item_prod1 = new javax.swing.JMenuItem();
        Item_tipo = new javax.swing.JMenuItem();
        Menu_ventas = new javax.swing.JMenu();
        Item_venta1 = new javax.swing.JMenuItem();
        Item_venta2 = new javax.swing.JMenuItem();
        Menu_proveedores = new javax.swing.JMenu();
        Item_prov1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal _ Pollería");
        setPreferredSize(new java.awt.Dimension(1200, 536));

        escritorio.setBackground(new java.awt.Color(237, 174, 73));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(224, 224, 224));

        Menu_sistema.setBackground(new java.awt.Color(224, 224, 224));
        Menu_sistema.setForeground(new java.awt.Color(0, 0, 0));
        Menu_sistema.setText("Sistema");
        Menu_sistema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Item_salir.setText("Salir");
        Menu_sistema.add(Item_salir);

        Item_sesion_close.setText("Cerrar sesión");
        Menu_sistema.add(Item_sesion_close);

        jMenuBar1.add(Menu_sistema);

        Menu_producto.setForeground(new java.awt.Color(0, 0, 0));
        Menu_producto.setText("Producto");
        Menu_producto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Item_prod1.setText("Ver productos");
        Item_prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_prod1ActionPerformed(evt);
            }
        });
        Menu_producto.add(Item_prod1);

        Item_tipo.setText("tipos");
        Menu_producto.add(Item_tipo);

        jMenuBar1.add(Menu_producto);

        Menu_ventas.setText("Ventas");
        Menu_ventas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Item_venta1.setText("Iniciar venta");
        Menu_ventas.add(Item_venta1);

        Item_venta2.setText("Mostrar venta");
        Menu_ventas.add(Item_venta2);

        jMenuBar1.add(Menu_ventas);

        Menu_proveedores.setText("Proveedores");
        Menu_proveedores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Item_prov1.setText("Ver Proveedores");
        Menu_proveedores.add(Item_prov1);

        jMenuBar1.add(Menu_proveedores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_prod1ActionPerformed
        String product = Vprod.produ;
        try {
        if(product==null){
            vprd = new Vprod();
            escritorio.add(vprd);
            escritorio.moveToFront(vprd);            
        }
        else{
            JOptionPane.showMessageDialog(null, "El menú productos ya está abierto");
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Item_prod1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_prod1;
    private javax.swing.JMenuItem Item_prov1;
    private javax.swing.JMenuItem Item_salir;
    private javax.swing.JMenuItem Item_sesion_close;
    private javax.swing.JMenuItem Item_tipo;
    private javax.swing.JMenuItem Item_venta1;
    private javax.swing.JMenuItem Item_venta2;
    private javax.swing.JMenu Menu_producto;
    private javax.swing.JMenu Menu_proveedores;
    private javax.swing.JMenu Menu_sistema;
    private javax.swing.JMenu Menu_ventas;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
